### ISSUE TITLE
Add website: Rhys Wynne

### ISSUE THREAD

**Issue by rhyswynne** [ralexander-phi/rss-blogroll-network#4]
I'd like to include my website in the RSS Blogroll Network crawler.

My RSS feed is located at: https://www.rhyswynne.co.uk/feed/

I have:
- ✅ Confirmed my site isn't currently listed in the network
-  ✅ An OPML blogroll which is discoverable at either
  - ✅ Using a `<source:blogroll ...>` element in my RSS feed
  - ✅ Using a `<link rel="blogroll" ...>` HTML element on my home screen; and/or
  - [ ] At the /.well-known/recommendations.opml path
- ✅ My OPML blogroll recommends at least two other websites or blogs
- ✅ My site is personal, non-commercial, and ad-free
- ✅ My site only contains human generated content (no AI other than spelling/grammar checkers)
- ✅ My site doesn't contain pornography, hate speech, or violent images (curse words are OK).
- ✅ I'm not blocking the crawler with `robots.txt`

**Comment by ralexander-phi** [comment]
I'll follow up on this one. Most of the other blogrolls use the xmlUrl to point at another feed, but your using the htmlUrl to point at websites. This is valid and the crawler is processing the links, but they aren't showing up on the web page yet.

**Comment by rhyswynne** [comment]
Okay. I can change to the feed URL (if present) if that makes it easier?

**Comment by ralexander-phi** [comment]
You can keep it as is. The htmlUrl is a valid way to build the OPML file, so I added support for that.

I just pushed a bunch more changes and now your page looks much better: https://alexsci.com/rss-blogroll-network/discover/feed-c2d8fce410dbc75ce21ee490648e1d70/

I'm only listing three of the sites in your blogroll as those are the only ones with RSS feeds. This project is sorta RSS-centric so I'm not listing the websites that don't (appear to) have web feeds. I may change that around later.

Ping me if anything looks off, I'm still very much in build mode for this project.
