### ISSUE TITLE
Add website: ttntm.me

### ISSUE THREAD

**Issue by ttntm** [ralexander-phi/rss-blogroll-network#5]
I'd like to include my website in the RSS Blogroll Network crawler.

My RSS feed is located at: https://ttntm.me/everything.xml

(just the blog: https://ttntm.me/blog/feed.xml)

I have:
- [x] Confirmed my site isn't currently listed in the network
- [x] An OPML blogroll which is discoverable at either
  - [ ] Using a `<source:blogroll ...>` element in my RSS feed
  - [x] Using a `<link rel="blogroll" ...>` HTML element on my home screen; and/or
  - [x] At the /.well-known/recommendations.opml path
- [x] My OPML blogroll recommends at least two other websites or blogs
- [x] My site is personal, non-commercial, and ad-free
- [x] My site only contains human generated content (no AI other than spelling/grammar checkers)
- [x] My site doesn't contain pornography, hate speech, or violent images (curse words are OK).
- [x] I'm not blocking the crawler with `robots.txt`

**Comment by ralexander-phi** [comment]
Hi Tom, I'd be happy to add your website.

However, it looks like your robots.txt is blocking the crawler. It starts with:

```
User-agent: *
Disallow: /everything.xml
Disallow: /blog/feed.xml
```

Can you update your robots.txt to allow our user-agent? Adding something like this to the bottom should work:
```
User-agent: Feed2Pages/0.1
Disallow:
```

I'd like to respect all robots.txt settings, so I won't be able to crawl the site as-is.

**Comment by ttntm** [comment]
@ralexander-phi oh shoot, sorry, I don't know how I missed that.

I've just whitelisted the crawler, thanks for the hint!

**Comment by ralexander-phi** [comment]
Great, I've added your site here: http://localhost:1313/discover/feed-10420918feef664f327101723c6ac281/

**Comment by ttntm** [comment]
Thanks 🙏
